### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by AugusDogus** [DoggyCraftDK/MyDog#9]
While starting the server I get the following error:

```
[21:56:47 ERROR]: Error occurred while enabling MyDog v0.0.8 (Is it up to date?)

	at dk.fido2603.mydog.PermissionsManager.<init>(PermissionsManager.java:27) ~[?:?]

	at dk.fido2603.mydog.MyDog.onEnable(MyDog.java:169) ~[?:?]

```

**Comment by AugusDogus** [comment]
Can you please create a release for 528f25afa30582e5a61fcba04ebb7dfcddccc8bd that includes a jar file for testing?

**Comment by Fido2603** [comment]
Working on it, trying to setup the GitHub package registry for hosting the files, it might work haha

**Comment by Fido2603** [comment]
It can now be downloaded from both the Packages and Releases tab!
